steps:
  # Run tests
  - name: 'node:18'
    id: 'run-tests'
    entrypoint: npm
    args: ['ci']
    env:
      - 'NODE_ENV=test'

  - name: 'node:18'
    id: 'test'
    entrypoint: npm
    args: ['test']
    env:
      - 'NODE_ENV=test'
      - 'DATABASE_URL=postgresql://test:test@localhost:5432/test_db'

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/samaanai-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/samaanai-api:latest'
      - '.'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/samaanai-api'

  # Run Prisma migrations
  - name: 'gcr.io/$PROJECT_ID/samaanai-api:$COMMIT_SHA'
    id: 'run-migrations'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npx prisma migrate deploy
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'
    secretEnv: ['DB_PASSWORD']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'samaanai-api'
      - '--image=gcr.io/$PROJECT_ID/samaanai-api:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=NODE_ENV=production,PORT=8080'
      - '--set-secrets=JWT_SECRET=jwt-secret:latest,JWT_REFRESH_SECRET=jwt-refresh-secret:latest,DATABASE_URL=database-url:latest'
      - '--add-cloudsql-instances=${_CLOUD_SQL_INSTANCE}'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=60s'
      - '--concurrency=80'
      - '--max-instances=100'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/db-password/versions/latest
      env: 'DB_PASSWORD'

substitutions:
  _REGION: 'us-central1'
  _CLOUD_SQL_INSTANCE: '${PROJECT_ID}:us-central1:samaanai-db'
  _DATABASE_URL: 'postgresql://samaanai_user@/samaanai?host=/cloudsql/${PROJECT_ID}:us-central1:samaanai-db'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

timeout: 1200s

images:
  - 'gcr.io/$PROJECT_ID/samaanai-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/samaanai-api:latest'